services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bin/dev
    volumes:
      - .:/rails
      - bundle:/usr/local/bundle
      - node_modules:/rails/node_modules
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=development
    tty: true
    stdin_open: true

  setup:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bin/setup
    volumes:
      - .:/rails
      - bundle:/usr/local/bundle
      - node_modules:/rails/node_modules
    environment:
      - RAILS_ENV=development
    profiles:
      - setup

volumes:
  bundle:
  node_modules:
