# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
#
# Configure Using Gemfile
# gem "pg"
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: web_hunt_development

test:
  <<: *default
  database: web_hunt_test

production:
  primary: &primary_production
    <<: *default
    database: web_hunt_production
    username: web_hunt
    password: <%= ENV["WEB_HUNT_DATABASE_PASSWORD"] %>
    url: <%= ENV["DATABASE_URL"] %>
